import './globals.css'
import Header from './Header';
import SupabaseListener from './components/supabase-listener';
import SupabaseProvider from './providers/supabase-provider';
import { createServerClient } from '@/lib/supabase-server';

import type { Database } from '@/lib/database.types';
import type { SupabaseClient } from '@supabase/auth-helpers-nextjs';

export type TypedSupabaseClient = SupabaseClient<Database>;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createServerClient();

  const {
    data: { session }
  } = await supabase.auth.getSession();

  return (
    <html lang="ja">
      <body>
        <SupabaseProvider session={session}>
          <SupabaseListener serverAccessToken={session?.access_token} />
            <Header />
            {children}
        </SupabaseProvider>
      </body>
    </html>
  )
}
